<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <url>
      <loc>{{route('home')}}</loc>
      <lastmod>2021-02-15</lastmod>
      <changefreq>daily</changefreq>
      <priority>1</priority>
   </url>
   <url>
        <loc>{{route('blog')}}</loc>
        <lastmod>2021-02-15</lastmod>
        <changefreq>monthly</changefreq>
        <priority>1</priority>
    </url>
    <url>
        <loc>{{route('login.get')}}</loc>
        <lastmod>2021-02-15</lastmod>
        <changefreq>monthly</changefreq>
        <priority>1</priority>
    </url>
    <url>
        <loc>{{route('signup.get')}}</loc>
        <lastmod>2021-02-15</lastmod>
        <changefreq>monthly</changefreq>
        <priority>1</priority>
    </url>
    <url>
        <loc>{{route('order.trace')}}</loc>
        <lastmod>2021-02-15</lastmod>
        <changefreq>monthly</changefreq>
        <priority>1</priority>
    </url>
    <url>
        <loc>{{route('shop')}}</loc>
        <lastmod>2021-02-15</lastmod>
        <changefreq>daily</changefreq>
        <priority>1</priority>
    </url>
    @forelse ($AllCategories as $Category)
     <url>
        <loc>{{route('shop.category' , $Category->slug)}}</loc>
        <lastmod>2021-02-15</lastmod>
        <changefreq>daily</changefreq>
        <priority>1</priority>
    </url>
    @empty
        
    @endforelse
    <url>
        <loc>{{route('shop.size' , 'mini_bb')}}</loc>
        <lastmod>2021-02-15</lastmod>
        <changefreq>daily</changefreq>
        <priority>1</priority>
    </url>
    <url>
        <loc>{{route('shop.size' , 'bb')}}</loc>
        <lastmod>2021-02-15</lastmod>
        <changefreq>daily</changefreq>
        <priority>1</priority>
    </url>
    <url>
        <loc>{{route('shop.size' , 'medium')}}</loc>
        <lastmod>2021-02-15</lastmod>
        <changefreq>daily</changefreq>
        <priority>1</priority>
    </url>
    <url>
        <loc>{{route('shop.size' , 'adult')}}</loc>
        <lastmod>2021-02-15</lastmod>
        <changefreq>daily</changefreq>
        <priority>1</priority>
    </url>
    <url>
        <loc>{{route('shop.size' , 'older')}}</loc>
        <lastmod>2021-02-15</lastmod>
        <changefreq>daily</changefreq>
        <priority>1</priority>
    </url>
    <url>
        <loc>{{route('shop.season','summer')}}</loc>
        <lastmod>2021-02-15</lastmod>
        <changefreq>daily</changefreq>
        <priority>1</priority>
    </url>
    <url>
        <loc>{{route('shop.season','winter')}}</loc>
        <lastmod>2021-02-15</lastmod>
        <changefreq>daily</changefreq>
        <priority>1</priority>
    </url>
    <url>
        <loc>{{route('shop.type','pajama')}}</loc>
        <lastmod>2021-02-15</lastmod>
        <changefreq>daily</changefreq>
        <priority>1</priority>
    </url>
    <url>
        <loc>{{route('shop.type','tshirt')}}</loc>
        <lastmod>2021-02-15</lastmod>
        <changefreq>daily</changefreq>
        <priority>1</priority>
    </url>
    <url>
        <loc>{{route('shop.type','pants')}}</loc>
        <lastmod>2021-02-15</lastmod>
        <changefreq>daily</changefreq>
        <priority>1</priority>
    </url>
    <url>
        <loc>{{route('shop.type','shoes')}}</loc>
        <lastmod>2021-02-15</lastmod>
        <changefreq>daily</changefreq>
        <priority>1</priority>
    </url>
    <url>
        <loc>{{route('shop.search')}}</loc>
        <lastmod>2021-02-15</lastmod>
        <changefreq>daily</changefreq>
        <priority>1</priority>
    </url>
    <url>
        <loc>{{route('contact')}}</loc>
        <lastmod>2021-02-15</lastmod>
        <changefreq>monthly</changefreq>
        <priority>1</priority>
    </url>
    <url>
        <loc>{{route('about')}}</loc>
        <lastmod>2021-02-15</lastmod>
        <changefreq>monthly</changefreq>
        <priority>1</priority>
    </url>
    <url>
        <loc>{{route('privacy.policy')}}</loc>
        <lastmod>2021-02-15</lastmod>
        <changefreq>monthly</changefreq>
        <priority>0.8</priority>
     </url>
     <url>
        <loc>{{route('return.policy')}}</loc>
        <lastmod>2021-02-15</lastmod>
        <changefreq>monthly</changefreq>
        <priority>0.8</priority>
     </url>
     @forelse ($AllProducts as $Product)
        <url>
            <loc>{{route('product',[$Product->id , $Product->slug])}}</loc>
            <lastmod>{{$Product->updated_at->format('Y-m-d')}}</lastmod>
            <changefreq>daily</changefreq>
            <priority>1</priority>
        </url>
     @empty
     @endforelse
     @forelse ($AllArticles as $Article)
        <url>
            <loc>{{route('blog.single',[$Article->id , $Article->slug])}}</loc>
            <lastmod>{{$Article->updated_at->format('Y-m-d')}}</lastmod>
            <changefreq>daily</changefreq>
            <priority>1</priority>
        </url>
    @empty
    @endforelse
</urlset> 